"""
This module implements a FastAPI server that provides endpoints for interacting with the DocumentAgent.
The server exposes four endpoints:

1. /ask (POST):
   - Receives a transcription (user's spoken text) and processes it synchronously through the DocumentAgent.
   - Returns the generated answer as a JSON response.

2. /transcribe (POST):
   - Receives a transcription from the Furhat frontend.
   - Processes the transcription asynchronously by passing it to the DocumentAgent.
   - Stores the agent's response for later retrieval.
   - Returns an acknowledgment that the transcription was received.

3. /response (GET):
   - Retrieves the latest response generated by the DocumentAgent.
   - Returns the response in a JSON format so that the Furhat frontend can vocalize it.

4. /get_docs (POST):
   - Retrieves a list of documents via get_list_docs().
   - If one document is found, returns it.
   - If no documents are found, returns an appropriate message.
   - If multiple documents are found, uses TextClassifier to rank them based on the transcription
     and returns the top-ranked document.

5. /engage (POST):
   - Retrieves document context, creates a combined text with the provided answer, generates a summary,
     and then creates a followup prompt.

The server integrates with a backend agent (DocumentAgent) which is responsible for managing the conversation flow,
retrieving relevant document context, and generating responses using an LLM.
"""

from fastapi import FastAPI, HTTPException, WebSocket
from pydantic import BaseModel
import uvicorn
import asyncio
import logging
from datetime import datetime

# Import the DocumentAgent and utility functions from the backend.
from my_furhat_backend.agents.document_agent import DocumentAgent
from my_furhat_backend.utils.util import (
    get_list_docs, 
    classify_text
)

from my_furhat_backend.db.session import init_db
from my_furhat_backend.perception.websocket_handler import perception_ws_handler

# Initialize the FastAPI application.
app = FastAPI()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class Transcription(BaseModel):
    content: str


class EngageRequest(BaseModel):
    document: str
    answer: str


# For demonstration purposes, using a simple in-memory store for the latest response.
latest_response = None

# Instantiate the DocumentAgent to handle LLM processing.
agent = DocumentAgent()


@app.on_event("startup")
def on_startup():
    init_db()
    logger.info("Database initialized.")


@app.post("/ask", response_model=dict)
async def ask_question(transcription: Transcription):
    global latest_response
    try:
        latest_response = await asyncio.to_thread(agent.run, transcription.content)
        response = {
            "status": "success",
            "response": latest_response,
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "question_length": len(transcription.content),
                "answer_length": len(latest_response)
            }
        }
        return response
    except Exception as e:
        logger.error(f"Error in ask endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/transcribe", response_model=dict)
async def transcribe(transcription: Transcription):
    global latest_response
    try:
        latest_response = await asyncio.to_thread(agent.run, transcription.content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    return {"status": "transcription received"}


@app.get("/response", response_model=dict)
async def get_response():
    if latest_response is None:
        return {"response": "No response generated yet."}
    return {"response": latest_response}


@app.post("/get_docs", response_model=dict)
async def get_docs(transcription: Transcription):
    try:
        docs = await asyncio.to_thread(get_list_docs)
        if not docs:
            return {"response": "No documents found."}
        if len(docs) == 1:
            return {"response": docs[0]}
        ranked_docs = await asyncio.to_thread(classify_text, transcription.content, docs)
        top_doc = list(ranked_docs.keys())[0] if ranked_docs else "No document ranked."
        return {"response": top_doc}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/engage", response_model=dict)
async def engage(engage_request: EngageRequest):
    try:
        prompt = await asyncio.to_thread(agent.engage, engage_request.document, engage_request.answer)
        response = {
            "status": "success",
            "prompt": prompt,
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "document": engage_request.document,
                "context_length": len(engage_request.answer)
            }
        }
        return response
    except Exception as e:
        logger.error(f"Error in engage endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.websocket("/ws/perception")
async def ws_perception(websocket: WebSocket):
    await perception_ws_handler(websocket)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)